# Generated by Django 6.0.6 on 2026-06-04 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('author', models.CharField(max_length=150, verbose_name='Автор')),
                ('status', models.CharField(choices=[('want', 'Хочу прочитать'), ('reading', 'Читаю'), ('done', 'Прочитана')], default='want', max_length=20, verbose_name='Статус')),
                ('rating', models.IntegerField(default=0, verbose_name='Оценка')),
                ('started', models.DateField(blank=True, null=True, verbose_name='Дата начала чтения')),
                ('finished', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
            },
        ),
    ]
